// AUTO-GENERATED by watchparty/tools/gen-action-contract.mjs
// Source of truth: watchparty/tools/action-contract-source.mjs
// Do not edit manually - run: node tools/gen-action-contract.mjs

const WPAction = (() => {
  'use strict';

  const ACTION = Object.freeze({
    STATUS_GET: 'status.get',
    STATUS_UPDATED: 'status.updated',
    STREMIO_STATUS_UPDATED: 'stremio.status.updated',
    PROFILE_UPDATED: 'profile.updated',
    SURFACE_READY: 'surface.ready',
    PROBE_SURFACE: 'surface.probe',
    OPEN_SIDEBAR: 'sidebar.open',
    BOOTSTRAP_PENDING: 'bootstrap.pending',
    SESSION_STATE_PUBLISH: 'session.state.publish',
    CONTROLLER_RELEASED: 'controller.released',
    CONTROLLER_LEASE_CLAIM: 'controller.lease.claim',
    CONTROLLER_LEASE_RELEASE: 'controller.lease.release',
    ACTIVE_VIDEO_LEASE_CLAIM: 'video.lease.claim',
    ACTIVE_VIDEO_LEASE_RELEASE: 'video.lease.release',
    ROOM_CREATE: 'room.create',
    ROOM_JOIN: 'room.join',
    ROOM_LEAVE: 'room.leave',
    ROOM_CHAT_EVENT: 'room.chat.appended',
    ROOM_TYPING_EVENT: 'room.typing.updated',
    ROOM_BOOKMARK_EVENT: 'room.bookmark.appended',
    ROOM_REACTION_EVENT: 'room.reaction.appended',
    ROOM_ERROR_EVENT: 'room.error',
    ROOM_VISIBILITY_UPDATE: 'room.visibility.update',
    ROOM_SETTINGS_UPDATE: 'room.settings.update',
    ROOM_OWNERSHIP_TRANSFER: 'room.ownership.transfer',
    SESSION_USERNAME_UPDATE: 'session.username.update',
    ROOM_READY_CHECK_UPDATE: 'room.readyCheck.update',
    ROOM_BOOKMARK_ADD: 'room.bookmark.add',
    ROOM_BOOKMARK_SEEK: 'room.bookmark.seek',
    ROOM_CHAT_SEND: 'room.chat.send',
    ROOM_TYPING_SEND: 'room.typing.send',
    ROOM_REACTION_SEND: 'room.reaction.send',
    ROOM_MEMBER_PRESENCE_PUBLISH: 'room.member.presence.publish',
    ROOM_MEMBER_PLAYBACK_STATUS_PUBLISH: 'room.member.playbackStatus.publish',
    ROOM_PLAYBACK_REQUEST_SYNC: 'room.playback.sync.request',
    ROOM_RESUME: 'room.resume',
    APP_OPTIONS_OPEN: 'app.options.open',
    APP_STREMIO_OPEN: 'app.stremio.open',
    CLIPBOARD_COPY: 'clipboard.copy',
    SERVER_DIAGNOSTICS_GET: 'server.diagnostics.get',
    LOCAL_LANDING_ACCESS_SYNC: 'localLandingAccess.sync',
    AUTH_KEY_SAVE: 'auth.key.save',
    AUTH_KEY_CLEAR: 'auth.key.clear',
    OFFSCREEN_COPY: 'offscreen.copy',
  });

  return ACTION;
})();

const WPActionRoutes = (() => {
  'use strict';

  return Object.freeze({
    STATUS_GET: Object.freeze({
      action: WPAction.STATUS_GET,
      sources: Object.freeze(['popup', 'sidepanel', 'options', 'watchparty-bridge']),
      target: 'background',
    }),
    STATUS_UPDATED: Object.freeze({
      action: WPAction.STATUS_UPDATED,
      sources: Object.freeze(['background']),
      target: 'extension-surfaces',
    }),
    STREMIO_STATUS_UPDATED: Object.freeze({
      action: WPAction.STREMIO_STATUS_UPDATED,
      sources: Object.freeze(['background']),
      target: 'watchparty-bridge',
    }),
    PROFILE_UPDATED: Object.freeze({
      action: WPAction.PROFILE_UPDATED,
      sources: Object.freeze(['background', 'stremio-profile']),
      target: 'background',
    }),
    SURFACE_READY: Object.freeze({
      action: WPAction.SURFACE_READY,
      sources: Object.freeze(['watchparty-bridge', 'stremio-content']),
      target: 'background',
    }),
    PROBE_SURFACE: Object.freeze({
      action: WPAction.PROBE_SURFACE,
      sources: Object.freeze(['background']),
      target: 'extension-surfaces',
    }),
    OPEN_SIDEBAR: Object.freeze({
      action: WPAction.OPEN_SIDEBAR,
      sources: Object.freeze(['background']),
      target: 'stremio-content',
    }),
    BOOTSTRAP_PENDING: Object.freeze({
      action: WPAction.BOOTSTRAP_PENDING,
      sources: Object.freeze(['background']),
      target: 'stremio-content',
    }),
    SESSION_STATE_PUBLISH: Object.freeze({
      action: WPAction.SESSION_STATE_PUBLISH,
      sources: Object.freeze(['stremio-content']),
      target: 'background',
    }),
    CONTROLLER_RELEASED: Object.freeze({
      action: WPAction.CONTROLLER_RELEASED,
      sources: Object.freeze(['stremio-content']),
      target: 'background',
    }),
    CONTROLLER_LEASE_CLAIM: Object.freeze({
      action: WPAction.CONTROLLER_LEASE_CLAIM,
      sources: Object.freeze(['stremio-content']),
      target: 'background',
    }),
    CONTROLLER_LEASE_RELEASE: Object.freeze({
      action: WPAction.CONTROLLER_LEASE_RELEASE,
      sources: Object.freeze(['stremio-content']),
      target: 'background',
    }),
    ACTIVE_VIDEO_LEASE_CLAIM: Object.freeze({
      action: WPAction.ACTIVE_VIDEO_LEASE_CLAIM,
      sources: Object.freeze(['stremio-content']),
      target: 'background',
    }),
    ACTIVE_VIDEO_LEASE_RELEASE: Object.freeze({
      action: WPAction.ACTIVE_VIDEO_LEASE_RELEASE,
      sources: Object.freeze(['stremio-content']),
      target: 'background',
    }),
    ROOM_CREATE: Object.freeze({
      action: WPAction.ROOM_CREATE,
      sources: Object.freeze(['popup', 'watchparty-bridge', 'background']),
      target: 'controller',
    }),
    ROOM_JOIN: Object.freeze({
      action: WPAction.ROOM_JOIN,
      sources: Object.freeze(['popup', 'watchparty-bridge', 'background']),
      target: 'controller',
    }),
    ROOM_LEAVE: Object.freeze({
      action: WPAction.ROOM_LEAVE,
      sources: Object.freeze(['overlay', 'popup', 'sidepanel']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_CHAT_EVENT: Object.freeze({
      action: WPAction.ROOM_CHAT_EVENT,
      sources: Object.freeze(['stremio-content', 'background']),
      target: 'extension-surfaces',
    }),
    ROOM_TYPING_EVENT: Object.freeze({
      action: WPAction.ROOM_TYPING_EVENT,
      sources: Object.freeze(['stremio-content', 'background']),
      target: 'extension-surfaces',
    }),
    ROOM_BOOKMARK_EVENT: Object.freeze({
      action: WPAction.ROOM_BOOKMARK_EVENT,
      sources: Object.freeze(['stremio-content', 'background']),
      target: 'extension-surfaces',
    }),
    ROOM_REACTION_EVENT: Object.freeze({
      action: WPAction.ROOM_REACTION_EVENT,
      sources: Object.freeze(['stremio-content', 'background']),
      target: 'stremio-content',
    }),
    ROOM_ERROR_EVENT: Object.freeze({
      action: WPAction.ROOM_ERROR_EVENT,
      sources: Object.freeze(['stremio-content', 'background']),
      target: 'extension-surfaces',
    }),
    ROOM_VISIBILITY_UPDATE: Object.freeze({
      action: WPAction.ROOM_VISIBILITY_UPDATE,
      sources: Object.freeze(['overlay']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_SETTINGS_UPDATE: Object.freeze({
      action: WPAction.ROOM_SETTINGS_UPDATE,
      sources: Object.freeze(['overlay']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_OWNERSHIP_TRANSFER: Object.freeze({
      action: WPAction.ROOM_OWNERSHIP_TRANSFER,
      sources: Object.freeze(['overlay']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    SESSION_USERNAME_UPDATE: Object.freeze({
      action: WPAction.SESSION_USERNAME_UPDATE,
      sources: Object.freeze(['overlay']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_READY_CHECK_UPDATE: Object.freeze({
      action: WPAction.ROOM_READY_CHECK_UPDATE,
      sources: Object.freeze(['overlay', 'sidepanel']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_BOOKMARK_ADD: Object.freeze({
      action: WPAction.ROOM_BOOKMARK_ADD,
      sources: Object.freeze(['overlay', 'sidepanel']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_BOOKMARK_SEEK: Object.freeze({
      action: WPAction.ROOM_BOOKMARK_SEEK,
      sources: Object.freeze(['sidepanel']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_CHAT_SEND: Object.freeze({
      action: WPAction.ROOM_CHAT_SEND,
      sources: Object.freeze(['overlay', 'sidepanel']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_TYPING_SEND: Object.freeze({
      action: WPAction.ROOM_TYPING_SEND,
      sources: Object.freeze(['overlay', 'sidepanel']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_REACTION_SEND: Object.freeze({
      action: WPAction.ROOM_REACTION_SEND,
      sources: Object.freeze(['overlay']),
      target: 'controller',
      requiresTrustedEvent: true,
    }),
    ROOM_MEMBER_PRESENCE_PUBLISH: Object.freeze({
      action: WPAction.ROOM_MEMBER_PRESENCE_PUBLISH,
      sources: Object.freeze(['stremio-content', 'background']),
      target: 'controller',
      activeVideoOnly: true,
    }),
    ROOM_MEMBER_PLAYBACK_STATUS_PUBLISH: Object.freeze({
      action: WPAction.ROOM_MEMBER_PLAYBACK_STATUS_PUBLISH,
      sources: Object.freeze(['stremio-content', 'background']),
      target: 'controller',
      activeVideoOnly: true,
    }),
    ROOM_PLAYBACK_REQUEST_SYNC: Object.freeze({
      action: WPAction.ROOM_PLAYBACK_REQUEST_SYNC,
      sources: Object.freeze(['overlay']),
      target: 'controller',
      requiresTrustedEvent: true,
      activeVideoOnly: true,
    }),
    ROOM_RESUME: Object.freeze({
      action: WPAction.ROOM_RESUME,
      sources: Object.freeze(['popup', 'options', 'watchparty-bridge']),
      target: 'background',
    }),
    APP_OPTIONS_OPEN: Object.freeze({
      action: WPAction.APP_OPTIONS_OPEN,
      sources: Object.freeze(['watchparty-bridge']),
      target: 'background',
    }),
    APP_STREMIO_OPEN: Object.freeze({
      action: WPAction.APP_STREMIO_OPEN,
      sources: Object.freeze(['popup', 'options', 'watchparty-bridge']),
      target: 'background',
    }),
    CLIPBOARD_COPY: Object.freeze({
      action: WPAction.CLIPBOARD_COPY,
      sources: Object.freeze(['shared-utils', 'options']),
      target: 'background',
    }),
    SERVER_DIAGNOSTICS_GET: Object.freeze({
      action: WPAction.SERVER_DIAGNOSTICS_GET,
      sources: Object.freeze(['options']),
      target: 'background',
    }),
    LOCAL_LANDING_ACCESS_SYNC: Object.freeze({
      action: WPAction.LOCAL_LANDING_ACCESS_SYNC,
      sources: Object.freeze(['options']),
      target: 'background',
    }),
    AUTH_KEY_SAVE: Object.freeze({
      action: WPAction.AUTH_KEY_SAVE,
      sources: Object.freeze(['stremio-profile']),
      target: 'background',
    }),
    AUTH_KEY_CLEAR: Object.freeze({
      action: WPAction.AUTH_KEY_CLEAR,
      sources: Object.freeze(['options']),
      target: 'background',
    }),
    OFFSCREEN_COPY: Object.freeze({
      action: WPAction.OFFSCREEN_COPY,
      sources: Object.freeze(['background']),
      target: 'offscreen',
    }),
  });
})();

const WPActionContract = (() => {
  'use strict';

  const routesByAction = Object.freeze(
    Object.values(WPActionRoutes).reduce((routes, route) => {
      if (route?.action) routes[route.action] = route;
      return routes;
    }, {})
  );

  function getRoute(action) {
    return routesByAction[action] || null;
  }

  function isKnownAction(action) {
    return !!getRoute(action);
  }

  function isAllowedSource(action, source) {
    return getRoute(action)?.sources?.includes(source) === true;
  }

  function isTarget(action, target) {
    return getRoute(action)?.target === target;
  }

  function requiresTrustedEvent(action) {
    return getRoute(action)?.requiresTrustedEvent === true;
  }

  function isActiveVideoOnly(action) {
    return getRoute(action)?.activeVideoOnly === true;
  }

  function getActionsForTarget(target) {
    return Object.freeze(
      Object.values(WPActionRoutes)
        .filter((route) => route?.target === target)
        .map((route) => route.action)
    );
  }

  return Object.freeze({
    getRoute,
    isKnownAction,
    isAllowedSource,
    isTarget,
    requiresTrustedEvent,
    isActiveVideoOnly,
    getActionsForTarget,
  });
})();
